// // // This file is automatically generated. Do not edit it directly.
// // import { createClient } from '@supabase/supabase-js';
// // import type { Database } from './types';

// // const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// // const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// // // Import the supabase client like this:
// // // import { supabase } from "@/integrations/supabase/client";

// // export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
// //   auth: {
// //     storage: localStorage,
// //     persistSession: true,
// //     autoRefreshToken: true,
// //   }
// // });
// // FILE: src/lib/api-client.ts
// // API client to connect to your Next.js backend

// const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

// class ApiClient {
//   private baseUrl: string;
//   private token: string | null = null;

//   constructor(baseUrl: string) {
//     this.baseUrl = baseUrl;
//     // Load token from localStorage
//     this.token = localStorage.getItem('auth_token');
//   }

//   setToken(token: string) {
//     this.token = token;
//     localStorage.setItem('auth_token', token);
//   }

//   clearToken() {
//     this.token = null;
//     localStorage.removeItem('auth_token');
//   }

//   private async request(endpoint: string, options: RequestInit = {}) {
//     const headers: HeadersInit = {
//       'Content-Type': 'application/json',
//       ...options.headers,
//     };

//     if (this.token) {
//       headers['Authorization'] = `Bearer ${this.token}`;
//     }

//     const response = await fetch(`${this.baseUrl}${endpoint}`, {
//       ...options,
//       headers,
//       credentials: 'include', // Send cookies
//     });

//     if (!response.ok) {
//       const error = await response.json().catch(() => ({ error: 'Request failed' }));
//       throw new Error(error.error || `HTTP ${response.status}`);
//     }

//     return response.json();
//   }

//   // Auth
//   async login(email: string, password: string) {
//     const data = await this.request('/api/auth/login', {
//       method: 'POST',
//       body: JSON.stringify({ email, password }),
//     });
//     if (data.session?.access_token) {
//       this.setToken(data.session.access_token);
//     }
//     return data;
//   }

//   async signup(email: string, password: string, fullName: string) {
//     const data = await this.request('/api/auth/signup', {
//       method: 'POST',
//       body: JSON.stringify({ email, password, fullName }),
//     });
//     if (data.session?.access_token) {
//       this.setToken(data.session.access_token);
//     }
//     return data;
//   }

//   async logout() {
//     this.clearToken();
//   }

//   // Websites
//   async getWebsites() {
//     return this.request('/api/websites');
//   }

//   async createWebsite(data: { name: string; url: string; domain: string }) {
//     return this.request('/api/websites', {
//       method: 'POST',
//       body: JSON.stringify(data),
//     });
//   }

//   async getWebsite(id: string) {
//     return this.request(`/api/websites/${id}`);
//   }

//   async updateWebsite(id: string, data: any) {
//     return this.request(`/api/websites/${id}`, {
//       method: 'PATCH',
//       body: JSON.stringify(data),
//     });
//   }

//   async deleteWebsite(id: string) {
//     return this.request(`/api/websites/${id}`, {
//       method: 'DELETE',
//     });
//   }

//   // Subscribers
//   async getSubscribers(websiteId?: string) {
//     const params = websiteId ? `?websiteId=${websiteId}` : '';
//     return this.request(`/api/subscribers${params}`);
//   }

//   async getWebsiteSubscribers(websiteId: string) {
//     return this.request(`/api/websites/${websiteId}/subscribers`);
//   }

//   async registerSubscriber(data: {
//     websiteId: string;
//     subscription: any;
//     platform: string;
//     browser?: string;
//     os?: string;
//   }) {
//     return this.request('/api/subscribers/register', {
//       method: 'POST',
//       body: JSON.stringify(data),
//     });
//   }

//   async deleteSubscriber(id: string) {
//     return this.request(`/api/subscribers/${id}`, {
//       method: 'DELETE',
//     });
//   }

//   // Notifications
//   async sendNotification(data: {
//     websiteId: string;
//     notification: {
//       title: string;
//       body: string;
//       icon?: string;
//       badge?: string;
//       image?: string;
//       url?: string;
//     };
//     targetSubscriberIds?: string[];
//     campaignId?: string;
//   }) {
//     return this.request('/api/notifications/send', {
//       method: 'POST',
//       body: JSON.stringify(data),
//     });
//   }

//   // Campaigns
//   async getCampaigns(websiteId?: string) {
//     const params = websiteId ? `?websiteId=${websiteId}` : '';
//     return this.request(`/api/campaigns${params}`);
//   }

//   async createCampaign(data: any) {
//     return this.request('/api/campaigns', {
//       method: 'POST',
//       body: JSON.stringify(data),
//     });
//   }

//   async getCampaign(id: string) {
//     return this.request(`/api/campaigns/${id}`);
//   }

//   async updateCampaign(id: string, data: any) {
//     return this.request(`/api/campaigns/${id}`, {
//       method: 'PATCH',
//       body: JSON.stringify(data),
//     });
//   }

//   async deleteCampaign(id: string) {
//     return this.request(`/api/campaigns/${id}`, {
//       method: 'DELETE',
//     });
//   }
// }

// export const api = new ApiClient(API_URL);

// src/integrations/supabase/client.ts
// Supabase DISABLED — backend auth is used instead

export const supabase = null;
